PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Users (
	id UUID PRIMARY KEY,
	name TEXT NOT NULL,
	sub TEXT NOT NULL,
	last_login DATETIME NOT NULL,
	created_at DATETIME NOT NULL,
	updated_at DATETIME NOT NULL,

	UNIQUE(sub)
);

CREATE TABLE IF NOT EXISTS Tokens (
	state TEXT PRIMARY KEY,
	userId TEXT NOT NULL,
	expires TIME NOT NULL,

	FOREIGN KEY(userId) REFERENCES Users(sub)
);
