name: Client check

on:
  push:
    paths:
      - "client/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "client/**"
      - ".github/workflows/**"

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json
      - name: Install dependencies
        working-directory: ./client
        run: npm ci
      - name: Run checks
        working-directory: ./client
        run: npm run ci
